config/routes.rb
Rails.application.routes.draw do
  root "marshall_warnings#index"
  resources :marshall_warnings
  resources :service_providers
  
end




# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marshall_warning.rb
class MarshallWarning < ApplicationRecord
  belongs_to :service_provider
end

app/models/service_provider.rb
class ServiceProvider < ApplicationRecord
  has_many :service_provider
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/marshall_warnings_controller.rb
class MarshallWarningsController < ApplicationController
  before_action :set_marshall_warning, only: %i[ show edit update destroy ]

  # GET /marshall_warnings or /marshall_warnings.json
  def index
    @marshall_warnings = MarshallWarning.all
  end

  # GET /marshall_warnings/1 or /marshall_warnings/1.json
  def show
  end

  # GET /marshall_warnings/new
  def new
    @marshall_warning = MarshallWarning.new
  end

  # GET /marshall_warnings/1/edit
  def edit
  end

  # POST /marshall_warnings or /marshall_warnings.json
  def create
    @marshall_warning = MarshallWarning.new(marshall_warning_params)

    respond_to do |format|
      if @marshall_warning.save
        format.html { redirect_to @marshall_warning, notice: "Marshall warning was successfully created." }
        format.json { render :show, status: :created, location: @marshall_warning }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @marshall_warning.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marshall_warnings/1 or /marshall_warnings/1.json
  def update
    respond_to do |format|
      if @marshall_warning.update(marshall_warning_params)
        format.html { redirect_to @marshall_warning, notice: "Marshall warning was successfully updated." }
        format.json { render :show, status: :ok, location: @marshall_warning }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @marshall_warning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marshall_warnings/1 or /marshall_warnings/1.json
  def destroy
    @marshall_warning.destroy
    respond_to do |format|
      format.html { redirect_to marshall_warnings_url, notice: "Marshall warning was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marshall_warning
      @marshall_warning = MarshallWarning.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marshall_warning_params
      params.require(:marshall_warning).permit(:service_provider_id, :registration_number, :fault, :action_comment)
    end
end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController
  before_action :set_service_provider, only: %i[ show edit update destroy ]

  # GET /service_providers or /service_providers.json
  def index
    @service_providers = ServiceProvider.all
  end

  # GET /service_providers/1 or /service_providers/1.json
  def show
  end

  # GET /service_providers/new
  def new
    @service_provider = ServiceProvider.new
  end

  # GET /service_providers/1/edit
  def edit
  end

  # POST /service_providers or /service_providers.json
  def create
    @service_provider = ServiceProvider.new(service_provider_params)

    respond_to do |format|
      if @service_provider.save
        format.html { redirect_to @service_provider, notice: "Service provider was successfully created." }
        format.json { render :show, status: :created, location: @service_provider }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_providers/1 or /service_providers/1.json
  def update
    respond_to do |format|
      if @service_provider.update(service_provider_params)
        format.html { redirect_to @service_provider, notice: "Service provider was successfully updated." }
        format.json { render :show, status: :ok, location: @service_provider }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_providers/1 or /service_providers/1.json
  def destroy
    @service_provider.destroy
    respond_to do |format|
      format.html { redirect_to service_providers_url, notice: "Service provider was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_provider
      @service_provider = ServiceProvider.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_provider_params
      params.require(:service_provider).permit(:name, :name_abreviation, :contact_email, :contact_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marshall_warnings_helper.rb
module MarshallWarningsHelper
end

app/helpers/service_providers_helper.rb
module ServiceProvidersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YarnwarningsPwa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/marshall_warnings/_form.html.erb
<%= form_with(model: marshall_warning) do |form| %>
  <% if marshall_warning.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marshall_warning.errors.count, "error") %> prohibited this marshall_warning from being saved:</h2>

      <ul>
        <% marshall_warning.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :service_provider_id %>
    <%= form.text_field :service_provider_id %>
  </div>

  <div class="field">
    <%= form.label :registration_number %>
    <%= form.text_field :registration_number %>
  </div>

  <div class="field">
    <%= form.label :fault %>
    <%= form.text_field :fault %>
  </div>

  <div class="field">
    <%= form.label :action_comment %>
    <%= form.text_field :action_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/marshall_warnings/edit.html.erb
<h1>Editing Marshall Warning</h1>

<%= render 'form', marshall_warning: @marshall_warning %>

<%= link_to 'Show', @marshall_warning %> |
<%= link_to 'Back', marshall_warnings_path %>

app/views/marshall_warnings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marshall Warnings</h1>

<table>
  <thead>
    <tr>
      <th>Service provider</th>
      <th>Registration number</th>
      <th>Fault</th>
      <th>Action comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marshall_warnings.each do |marshall_warning| %>
      <tr>
        <td><%= marshall_warning.service_provider_id %></td>
        <td><%= marshall_warning.registration_number %></td>
        <td><%= marshall_warning.fault %></td>
        <td><%= marshall_warning.action_comment %></td>
        <td><%= link_to 'Show', marshall_warning %></td>
        <td><%= link_to 'Edit', edit_marshall_warning_path(marshall_warning) %></td>
        <td><%= link_to 'Destroy', marshall_warning, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marshall Warning', new_marshall_warning_path %>

app/views/marshall_warnings/new.html.erb
<h1>New Marshall Warning</h1>

<%= render 'form', marshall_warning: @marshall_warning %>

<%= link_to 'Back', marshall_warnings_path %>

app/views/marshall_warnings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service provider:</strong>
  <%= @marshall_warning.service_provider_id %>
</p>

<p>
  <strong>Registration number:</strong>
  <%= @marshall_warning.registration_number %>
</p>

<p>
  <strong>Fault:</strong>
  <%= @marshall_warning.fault %>
</p>

<p>
  <strong>Action comment:</strong>
  <%= @marshall_warning.action_comment %>
</p>

<%= link_to 'Edit', edit_marshall_warning_path(@marshall_warning) %> |
<%= link_to 'Back', marshall_warnings_path %>

app/views/service_providers/_form.html.erb
<%= form_with(model: service_provider) do |form| %>
  <% if service_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_provider.errors.count, "error") %> prohibited this service_provider from being saved:</h2>

      <ul>
        <% service_provider.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :name_abreviation %>
    <%= form.text_field :name_abreviation %>
  </div>

  <div class="field">
    <%= form.label :contact_email %>
    <%= form.text_field :contact_email %>
  </div>

  <div class="field">
    <%= form.label :contact_name %>
    <%= form.text_field :contact_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/service_providers/edit.html.erb
<h1>Editing Service Provider</h1>

<%= render 'form', service_provider: @service_provider %>

<%= link_to 'Show', @service_provider %> |
<%= link_to 'Back', service_providers_path %>

app/views/service_providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Name abreviation</th>
      <th>Contact email</th>
      <th>Contact name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_providers.each do |service_provider| %>
      <tr>
        <td><%= service_provider.name %></td>
        <td><%= service_provider.name_abreviation %></td>
        <td><%= service_provider.contact_email %></td>
        <td><%= service_provider.contact_name %></td>
        <td><%= link_to 'Show', service_provider %></td>
        <td><%= link_to 'Edit', edit_service_provider_path(service_provider) %></td>
        <td><%= link_to 'Destroy', service_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Provider', new_service_provider_path %>

app/views/service_providers/new.html.erb
<h1>New Service Provider</h1>

<%= render 'form', service_provider: @service_provider %>

<%= link_to 'Back', service_providers_path %>

app/views/service_providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service_provider.name %>
</p>

<p>
  <strong>Name abreviation:</strong>
  <%= @service_provider.name_abreviation %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @service_provider.contact_email %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @service_provider.contact_name %>
</p>

<%= link_to 'Edit', edit_service_provider_path(@service_provider) %> |
<%= link_to 'Back', service_providers_path %>